import assert from 'node:assert/strict';
import vm from 'node:vm';
import { writeFile } from 'node:fs/promises';
import { runtime } from './reception-runtime.mjs';
import { validateEntry, csvCell } from '../src/reception.js';
import { receptionPage, receptionAdminPage } from '../src/reception_page.js';
const { mf, db, kv } = await runtime();
const origin = 'https://kabukiplus.com';
const api = '/api/kerakabuki/reception/2026';
const base = '/kerakabuki/reception/2026';
const manager = { cookie: 'kl_session=local-manager' };
const checks = [];
const check = (name, value) => { assert.ok(value, name);checks.push(name); };
const entry = (overrides = {}) => ({ request_id: crypto.randomUUID(), name: '動作確認 太郎', kana: 'どうさかくにん たろう', contact_method: 'none', donation_declared: false, consent: true, source: 'qr', ...overrides });
async function call(path, method = 'GET', body, extra = {}) {
  return mf.dispatchFetch(origin + path, { method, headers: { ...(body ? { 'content-type': 'application/json', origin } : {}), ...extra }, ...(body ? { body: JSON.stringify(body) } : {}) });
}
try {
  for (const page of [receptionPage(), receptionPage({ paper: true }), receptionAdminPage()]) {
    for (const m of page.matchAll(/<script>([\s\S]*?)<\/script>/g)) new vm.Script(m[1]);
  }
  check('生成した来場者・担当者画面のJavaScript構文', true);
  check('不要な住所・メールは保存しない', validateEntry(entry({ email: 'discard@example.com', address: 'discard' })).email === '');
  assert.throws(() => validateEntry(entry({ contact_method: 'post' })));checks.push('郵送希望には住所が必要');
  assert.throws(() => validateEntry(entry({ contact_method: 'email', email: 'bad' })));checks.push('不正メールを拒否');
  assert.throws(() => validateEntry(entry({ consent: false })));checks.push('利用目的の確認が必要');
  const form = await call(base);check('来場者画面はログイン不要', form.status === 200);
  check('個人情報を扱う画面をキャッシュしない', form.headers.get('cache-control').includes('no-store'));
  check('未ログインの一覧を拒否', (await call(api + '/admin')).status === 401);
  check('未ログインのCSVを拒否', (await call(api + '/admin/export')).status === 401);
  check('一般メンバーを拒否', (await call(api + '/admin', 'GET', undefined, { cookie: 'kl_session=local-member' })).status === 403);
  check('別団体の管理者を拒否', (await call(api + '/admin', 'GET', undefined, { cookie: 'kl_session=other-manager' })).status === 403);
  check('担当者の一覧を許可', (await call(api + '/admin', 'GET', undefined, manager)).status === 200);
  check('他サイトからの送信を拒否', (await call(api, 'POST', entry(), { origin: 'https://other.example' })).status === 403);
  check('同意なしの送信を拒否', (await call(api, 'POST', entry({ consent: false }))).status === 400);
  check('祝儀未選択を拒否', (await call(api, 'POST', entry({ donation_declared: undefined }))).status === 400);
  check('公開フォームから紙入力を偽装できない', (await call(api, 'POST', entry({ source: 'paper', paper_ref: 'A-1' }))).status === 401);
  check('無効な郵便番号を拒否', (await call(api + '/postal?code=123')).status === 400);
  const visit = entry();const sent = await call(api, 'POST', visit);assert.equal(sent.status, 200, await sent.clone().text());
  const first = await sent.json();check('観劇のみの記帳と受付番号発行', /^R8-\d+$/.test(first.receipt));
  const retry = await (await call(api, 'POST', visit)).json();check('再送時に同じ受付番号を返す', retry.receipt === first.receipt);
  check('同じ送信番号で別の内容を上書きしない', (await call(api, 'POST', { ...visit, name: '変更' })).status === 409);
  const post = entry({ name: '=1+1', contact_method: 'post', postal_code: '０１２－３４５６', address: '架空県確認市確認町', address_extra: '1-2 検証ビル3号', donation_declared: true, donor_name: '検証会社 代表者' });
  check('全角郵便番号・祝儀名義を受け付ける', (await call(api, 'POST', post)).status === 200);
  check('メール希望を受け付ける', (await call(api, 'POST', entry({ contact_method: 'email', email: 'sample@example.com' }))).status === 200);
  check('担当者の紙転記を受け付ける', (await call(api, 'POST', entry({ source: 'paper', paper_ref: 'A・1ページ・2行' }), manager)).status === 200);
  const list = await (await call(api + '/admin', 'GET', undefined, manager)).json();
  check('二重送信で件数が増えない', list.totals.total === 4);
  check('祝儀の申告だけでは受領済みにしない', list.totals.pending === 1 && list.totals.received === 0);
  check('送信トークンを一覧に出さない', list.entries.every(r => !('request_id' in r) && !('payload_hash' in r)));
  const donor = list.entries.find(r => r.donation_declared);
  const patch = { revision: donor.revision, received: true, amount_yen: 10000, staff_note: '袋と中身を照合済み' };
  check('担当者以外は受領確認できない', (await call(api + '/admin/' + donor.number, 'PATCH', patch)).status === 401);
  check('受領前の金額入力を拒否', (await call(api + '/admin/' + donor.number, 'PATCH', { ...patch, received: false }, manager)).status === 400);
  const edits = await Promise.all([call(api + '/admin/' + donor.number, 'PATCH', patch, manager), call(api + '/admin/' + donor.number, 'PATCH', patch, manager)]);
  check('同時更新は一方のみ成功し他方は競合を返す', edits.map(r => r.status).sort().join(',') === '200,409');
  check('受領操作の履歴を1件保存', (await db.prepare('SELECT COUNT(*) AS n FROM reception_audit').first()).n === 1);
  const after = await (await call(api + '/admin', 'GET', undefined, manager)).json();
  check('受領金額を集計', after.totals.received === 1 && after.totals.amount === 10000);
  const postalCSV = await (await call(api + '/admin/export?audience=post', 'GET', undefined, manager)).text();
  check('郵送CSVは希望者のみ、祝儀情報は含めない', postalCSV.includes('検証ビル') && !postalCSV.includes('sample@example.com') && !postalCSV.includes('金額') && !postalCSV.includes('照合済み'));
  check('CSV数式注入と郵便番号先頭ゼロ対策', postalCSV.includes("'=1+1") && postalCSV.includes('012-3456') && csvCell('@cmd').includes("'@cmd"));
  const emailCSV = await (await call(api + '/admin/export?audience=email', 'GET', undefined, manager)).text();
  check('メールCSVはメール希望者だけを含む', emailCSV.includes('sample@example.com') && !emailCSV.includes('検証ビル'));
  check('管理者が名前や連絡先を訂正できる', (await call(api+'/admin/'+donor.number,'PATCH',{ revision:1,received:true,amount_yen:10000,staff_note:'名義確認\n連絡先訂正',entry:{name:'訂正後の架空名',contact_method:'email',email:'corrected@example.com'}},manager)).status===200);
  const corrected=await db.prepare('SELECT * FROM reception_entries WHERE number=?').bind(donor.number).first();
  check('案内方法の変更時に不要な住所を消し祝儀は保持', corrected.address===''&&corrected.email==='corrected@example.com'&&corrected.amount_yen===10000&&corrected.donation_declared===1);
  check('訂正の監査履歴と改行メモを保持', (await db.prepare('SELECT COUNT(*) AS n FROM reception_audit').first()).n===2&&corrected.staff_note.includes('\n'));
  check('未知の年度へは記録できない', (await call('/api/kerakabuki/reception/2027', 'POST', entry())).status !== 200);
  const sw = await (await call('/sw.js')).text();check('Service Workerは受付ページを保存しない', sw.includes("url.pathname.startsWith('/kerakabuki/reception/')"));
  check('記念画像をダウンロードできる', (await call(base + '/commemorative.svg')).headers.get('content-type').startsWith('image/svg+xml'));
  const pngResponse = await call(base + '/commemorative.png');
  const pngBytes = new Uint8Array(await pngResponse.arrayBuffer());
  check('スマホ用PNGを直接配布できる', pngResponse.headers.get('content-type')==='image/png' && pngBytes[0]===137 && pngBytes[1]===80 && pngBytes.length>1000);
  // ページング境界を実D1で確認。
  const now = new Date().toISOString();
  await db.batch(Array.from({ length: 101 }, (_, i) => db.prepare("INSERT INTO reception_entries (request_id,payload_hash,event_id,name,contact_method,donation_declared,source,created_at,updated_at) VALUES (?,?,'2026',?,'none',0,'qr',?,?)").bind(crypto.randomUUID(),'fixture','架空データ'+i,now,now)));
  const page1 = await (await call(api + '/admin', 'GET', undefined, manager)).json();
  const page2 = await (await call(api + '/admin?cursor=' + page1.next, 'GET', undefined, manager)).json();
  check('100件を超えても欠落なくページング', page1.entries.length === 100 && page2.entries.length === 5 && page2.next === null);
  const masterId='local-master';await kv.put('master_users',JSON.stringify([masterId]));await kv.put('session:local-master',JSON.stringify({userId:masterId}));
  check('既存のマスター権限を利用できる', (await call(api+'/admin','GET',undefined,{cookie:'kl_session=local-master'})).status===200);
  const proxyBase = entry({ name:'架空の持参者', contact_method:'email',email:'carrier@example.com',proxy_gifts:[{name:'代理名義A',contact_method:'unknown'},{name:'代理名義B',contact_method:'post',postal_code:'5014303',address:'岐阜県郡上市明宝気良',address_extra:'検証用123',contact_confirmed:true}] });
  check('名義人不明の代理祝儀を拒否', (await call(api,'POST',entry({proxy_gifts:[{name:'',contact_method:'unknown'}]}))).status===400);
  check('本人の希望確認なしに代理郵送を登録できない', (await call(api,'POST',{...proxyBase,proxy_gifts:[{...proxyBase.proxy_gifts[1],contact_confirmed:false}]})).status===400);
  check('一度に11件以上の代理祝儀を拒否', (await call(api,'POST',entry({proxy_gifts:Array.from({length:11},()=>proxyBase.proxy_gifts[0])}))).status===400);
  check('祝儀なしのお届けのみを拒否', (await call(api,'POST',entry({attending:false}))).status===400);
  const beforeProxy=await db.prepare('SELECT COUNT(*) AS n, SUM(attending) AS visitors FROM reception_entries').first();
  const proxyResponses=await Promise.all([call(api,'POST',proxyBase),call(api,'POST',proxyBase)]);
  for(const r of proxyResponses)assert.equal(r.status,200,await r.clone().text());
  const proxyReceipts=await Promise.all(proxyResponses.map(r=>r.json()));
  check('同時再送した複数代理祝儀が同じ受付番号を返す',JSON.stringify(proxyReceipts[0])===JSON.stringify(proxyReceipts[1])&&proxyReceipts[0].proxy_receipts.length===2);
  const afterProxy=await db.prepare('SELECT COUNT(*) AS n, SUM(attending) AS visitors FROM reception_entries').first();
  check('代理名義人を観劇の記帳数に加えない',afterProxy.n===beforeProxy.n+3&&afterProxy.visitors===beforeProxy.visitors+1);
  const proxyRows=(await db.prepare("SELECT * FROM reception_entries WHERE name LIKE '代理名義%' ORDER BY number").all()).results;
  check('代理の未確認連絡先へ持参者の連絡先をコピーしない',proxyRows[0].contact_confirmed===0&&proxyRows[0].email===''&&proxyRows[0].address==='');
  const proxyList=await (await call(api+'/admin','GET',undefined,manager)).json();
  const proxyPage=await (await call(api+'/admin?cursor='+proxyList.next,'GET',undefined,manager)).json();
  check('管理画面に持参者との紐付けを返す',proxyPage.entries.some(r=>r.name==='代理名義A'&&r.carrier_name==='架空の持参者'));
  const proxyPostal=await (await call(api+'/admin/export?audience=post','GET',undefined,manager)).text();
  check('代理名義人自身の住所を郵送CSVに出力',proxyPostal.includes('代理名義B')&&proxyPostal.includes('検証用123')&&!proxyPostal.includes('代理名義A')&&!proxyPostal.includes('carrier@example.com'));
  const giftA=proxyRows[0];
  const giftPatch={revision:0,received:true,amount_yen:5000,staff_note:'代理袋Aのみ受領'};
  check('代理の一袋だけ受領確認できる',(await call(api+'/admin/'+giftA.number,'PATCH',giftPatch,manager)).status===200);
  check('他の祝儀袋の受領状態に影響しない',(await db.prepare('SELECT received FROM reception_entries WHERE number=?').bind(proxyRows[1].number).first()).received===0);
  check('代理人の案内先訂正には本人確認が必要',(await call(api+'/admin/'+giftA.number,'PATCH',{...giftPatch,revision:1,entry:{contact_method:'email',email:'donor@example.com'}},manager)).status===400);
  check('確認済みの名義人の案内先を訂正できる',(await call(api+'/admin/'+giftA.number,'PATCH',{...giftPatch,revision:1,entry:{contact_method:'email',email:'donor@example.com',contact_confirmed:true}},manager)).status===200);
  const delivery=await call(api,'POST',entry({attending:false,proxy_gifts:[{name:'お届けのみ名義',contact_method:'unknown'}]}));
  check('代理祝儀のお届けのみを受け付ける',delivery.status===200);
  const delivered=(await delivery.json()).receipt;
  check('お届けのみの持参者も観劇数に加えない',(await db.prepare('SELECT attending FROM reception_entries WHERE number=?').bind(Number(delivered.slice(3))).first()).attending===0);
  const countBeforeInvalid=(await db.prepare('SELECT COUNT(*) AS n FROM reception_entries').first()).n;
  await call(api,'POST',entry({proxy_gifts:[{name:'有効名義',contact_method:'unknown'},{name:'不正名義',contact_method:'email',email:'invalid',contact_confirmed:true}]}));
  check('一袋の入力が不正なら一式を保存しない',(await db.prepare('SELECT COUNT(*) AS n FROM reception_entries').first()).n===countBeforeInvalid);
  await writeFile('test-results.json', JSON.stringify({ tested_at: new Date().toISOString(), passed: checks.length, checks }, null, 2));
  console.log(JSON.stringify({ passed: checks.length, checks }, null, 2));
} finally { await mf.dispose(); }
